---
- name: wget, tar, http, php package remove, /etc/httpd, /var/www/html delete
  hosts: web
  gather_facts: yes
  ignore_errors: yes
  tasks:

  - name: package remove
    dnf:
      name:
        - wget
        - tar
        - httpd
        - php
        - php-cli
        - php-common
        - php-curl
        - php-gd
        - php-opcache
        - php-mysqlnd
      state: absent
      autoremove: yes

  - name: directory remove
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /etc/httpd
      - /var/www/html
      - /root/wordpress
      - /root/wordpress-5.7.8-ko-KR.tar.gz

  - name: firewall init
    firewalld:
      port: 80/tcp
      state: disabled